server:
  port: 8000

spring:
  cache:
    type: redis

  # Redis DB Config.
  redis:
    host: localhost
    port: 6379
    password: 12345
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2

  # Maria DB Config.
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jwt_201012?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 12345
    initialization-mode: always

  # JPA Config.
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      # create-drop, update.
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        sql_comments: true

  thymeleaf:
    cache: false
    encoding: UTF-8

  # Message Internationalization.
  messages:
    basename: classpath:i18n/success_messages, classpath:i18n/error_messages, classpath:i18n/web_messages
    encoding: UTF-8
    cache-duration:

logging:
  level:
    org.springframework.web: debug
    org.hibernate.type: info
  file:
    name: C:\Users\son\spring-boot-2-jwt-201024.log

# JWT Authentication key.
app:
  jwt-secret-key: $polling$app$jwt$secret$key$256$